name: Build Tauri App

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install webkit2gtk (Linux only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev \
            build-essential curl wget libssl-dev libgtk-3-dev \
            libayatana-appindicator3-dev librsvg2-dev
            
      - name: Install app dependencies
        run: |
          npm install
          npm install --save-dev @tauri-apps/cli
          
      - name: Build app
        run: |
          npm run tauri build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-build-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/${{ matrix.platform }}/${{ matrix.platform }}-app.zip
          asset_name: ${{ matrix.platform }}-app.zip
          asset_content_type: application/zip
